services:
  db:
    image: gabodev9090/disruptica-db:1.0
    container_name: disruptica-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app-network
  backend:
    depends_on:
      - db
    build: 
      context: ./backend-disruptica
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      CORS_WHITELIST: ${CORS_WHITELIST}
      PORT: ${PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend-disruptica
      args:
        VITE_BACKEND_URL: http://localhost:3000
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
